name: virtual-lenny
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h6fa692b_0
  - python_abi=3.10=2_cp310
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.10.1=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alembic==1.18.2
      - apify-client==2.4.0
      - apify-shared==2.2.0
      - arrow==1.4.0
      - async-timeout==4.0.3
      - asyncer==0.0.8
      - aws-cdk-asset-awscli-v1==2.2.263
      - aws-cdk-asset-kubectl-v20==2.1.4
      - aws-cdk-asset-node-proxy-agent-v6==2.1.0
      - aws-cdk-assets==1.204.0
      - aws-cdk-aws-acmpca==1.204.0
      - aws-cdk-aws-apigatewayv2==1.204.0
      - aws-cdk-aws-apigatewayv2-alpha==2.114.1a0
      - aws-cdk-aws-apigatewayv2-integrations==1.204.0
      - aws-cdk-aws-apigatewayv2-integrations-alpha==2.114.1a0
      - aws-cdk-aws-applicationautoscaling==1.204.0
      - aws-cdk-aws-autoscaling-common==1.204.0
      - aws-cdk-aws-certificatemanager==1.204.0
      - aws-cdk-aws-cloudformation==1.204.0
      - aws-cdk-aws-cloudwatch==1.204.0
      - aws-cdk-aws-codeguruprofiler==1.204.0
      - aws-cdk-aws-codestarnotifications==1.204.0
      - aws-cdk-aws-ec2==1.204.0
      - aws-cdk-aws-ecr==1.204.0
      - aws-cdk-aws-ecr-assets==1.204.0
      - aws-cdk-aws-efs==1.204.0
      - aws-cdk-aws-elasticloadbalancingv2==1.204.0
      - aws-cdk-aws-events==1.204.0
      - aws-cdk-aws-iam==1.204.0
      - aws-cdk-aws-kms==1.204.0
      - aws-cdk-aws-lambda==1.204.0
      - aws-cdk-aws-lambda-python-alpha==2.236.0a0
      - aws-cdk-aws-logs==1.204.0
      - aws-cdk-aws-route53==1.204.0
      - aws-cdk-aws-s3==1.204.0
      - aws-cdk-aws-s3-assets==1.204.0
      - aws-cdk-aws-servicediscovery==1.204.0
      - aws-cdk-aws-signer==1.204.0
      - aws-cdk-aws-sns==1.204.0
      - aws-cdk-aws-sqs==1.204.0
      - aws-cdk-aws-ssm==1.204.0
      - aws-cdk-cloud-assembly-schema==48.20.0
      - aws-cdk-core==1.204.0
      - aws-cdk-custom-resources==1.204.0
      - aws-cdk-cx-api==1.204.0
      - aws-cdk-lib==2.237.0
      - aws-cdk-region-info==1.204.0
      - aws-lambda-builders==1.62.0
      - aws-sam-cli==1.153.1
      - aws-sam-translator==1.106.0
      - awscrt==0.29.2
      - beautifulsoup4==4.14.3
      - binaryornot==0.4.4
      - boto3==1.42.26
      - boto3-stubs==1.42.38
      - botocore==1.42.38
      - botocore-stubs==1.42.38
      - cachetools==6.2.6
      - cattrs==25.3.0
      - cffi==2.0.0
      - cfn-lint==1.43.4
      - chardet==5.2.0
      - chevron==0.14.0
      - click==8.1.8
      - colorama==0.4.6
      - colorlog==6.10.1
      - constructs==10.4.5
      - contourpy==1.3.2
      - cookiecutter==2.6.0
      - cryptography==46.0.4
      - dataclasses-json==0.6.7
      - datasets==4.5.0
      - dateparser==1.2.2
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - dspy==3.1.2
      - dspy-ai==3.1.2
      - fastuuid==0.14.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - gepa==0.0.24
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.49.0.dev0
      - google-auth-httplib2==0.3.0
      - google-genai==1.60.0
      - googleapis-common-protos==1.72.0
      - graphviz==0.21
      - greenlet==3.3.1
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - httplib2==0.31.2
      - httpx-sse==0.4.3
      - huggingface-hub==1.3.4
      - impit==0.9.3
      - jiter==0.12.0
      - jmespath==1.0.1
      - jsii==1.126.0
      - json-repair==0.55.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.9
      - langchain==1.2.7
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.7
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.7
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.3
      - langsmith==0.6.6
      - litellm==1.81.5
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - mypy-boto3-apigateway==1.42.3
      - mypy-boto3-cloudformation==1.42.3
      - mypy-boto3-ecr==1.42.13
      - mypy-boto3-iam==1.42.4
      - mypy-boto3-kinesis==1.42.3
      - mypy-boto3-lambda==1.42.37
      - mypy-boto3-s3==1.42.37
      - mypy-boto3-schemas==1.42.3
      - mypy-boto3-secretsmanager==1.42.8
      - mypy-boto3-signer==1.42.7
      - mypy-boto3-sqs==1.42.3
      - mypy-boto3-stepfunctions==1.42.3
      - mypy-boto3-sts==1.42.3
      - mypy-boto3-xray==1.42.3
      - mypy-extensions==1.1.0
      - numpy==2.2.6
      - openai==2.16.0
      - optuna==4.7.0
      - ormsgpack==1.12.2
      - pillow==12.1.0
      - pinecone-client==6.0.0
      - pinecone-plugin-interface==0.0.7
      - portalocker==3.2.0
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==5.29.5
      - publication==0.0.3
      - pyarrow==23.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pydantic-settings==2.12.0
      - pyopenssl==25.3.0
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - pytube==15.0.0
      - qdrant-client==1.16.2
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scrapetube==2.6.0
      - sentence-transformers==5.2.2
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - sqlalchemy==2.0.46
      - tenacity==9.1.2
      - text-unidecode==1.3
      - textgrad==0.1.8
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - tomlkit==0.14.0
      - transformers==5.0.0
      - typeguard==2.13.3
      - types-awscrt==0.31.1
      - types-s3transfer==0.16.0
      - typing-inspect==0.9.0
      - tzlocal==5.3.1
      - uritemplate==4.2.0
      - uuid-utils==0.14.0
      - watchdog==4.0.2
      - websockets==15.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - youtube-transcript-api==0.6.3
      - yt-dlp==2025.12.8
      - zstandard==0.25.0
